/*
0 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HCI;

import java.awt.AWTException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfPoint;
import org.opencv.core.Scalar;
import org.opencv.core.Size;
import org.opencv.imgproc.Imgproc;
import org.opencv.videoio.VideoCapture;

/**
 *
 * @author AVENGERS
 */
public class Dashboard extends javax.swing.JFrame implements Runnable {
     Thread t;
     VideoCapture video;
     
    /**
     * Creates new form Dashboard
     */
    public Dashboard() throws AWTException {
        initComponents();
        ImageIcon img=new ImageIcon(getClass().getResource("/Image/hcilogo.png"));
        Image img1= img.getImage().getScaledInstance(lo.getHeight(),lo.getWidth(),Image.SCALE_SMOOTH);
        lo.setIcon(new ImageIcon(img1));
        
        ImageIcon img3=new ImageIcon(getClass().getResource("/Image/or.jpg"));
        Image img4= img3.getImage().getScaledInstance(original.getHeight(),original.getWidth(),Image.SCALE_SMOOTH);
        original.setIcon(new ImageIcon(img4));
        
        ImageIcon img5=new ImageIcon(getClass().getResource("/Image/or.jpg"));
        Image img6= img5.getImage().getScaledInstance(HSV.getHeight(),HSV.getWidth(),Image.SCALE_SMOOTH);
        HSV.setIcon(new ImageIcon(img6));
        titlebarsetting();
        
    }
void titlebarsetting()
        {
            this.setTitle("Dashboard");
            Image img2 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/titlelogo.png"));
            this.setIconImage(img2);
        }
public static BufferedImage matToBufferedImage(Mat matrix) {  
		int cols = matrix.cols();  
		int rows = matrix.rows();  
		int elemSize = (int)matrix.elemSize();  
		byte[] data = new byte[cols * rows * elemSize];  
		int type;  
		matrix.get(0, 0, data);  
		switch (matrix.channels()) {  
		case 1:  
			type = BufferedImage.TYPE_BYTE_GRAY;  
			break;  
		case 3:  
			type = BufferedImage.TYPE_3BYTE_BGR;  
			// bgr to rgb  
			byte b;  
			for(int i=0; i<data.length; i=i+3) {  
				b = data[i];  
				data[i] = data[i+2];  
				data[i+2] = b;  
			}  
			break;  
		default:  
			return null;  
		}  
		BufferedImage image2 = new BufferedImage(cols, rows, type);  
		image2.getRaster().setDataElements(0, 0, cols, rows, data);  
		return image2;  
	}  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HSV = new javax.swing.JLabel();
        original = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        s1 = new javax.swing.JSlider();
        s3 = new javax.swing.JSlider();
        s2 = new javax.swing.JSlider();
        s4 = new javax.swing.JSlider();
        s5 = new javax.swing.JSlider();
        s6 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        s7 = new javax.swing.JSlider();
        s9 = new javax.swing.JSlider();
        s8 = new javax.swing.JSlider();
        s10 = new javax.swing.JSlider();
        s11 = new javax.swing.JSlider();
        s12 = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        s13 = new javax.swing.JSlider();
        s15 = new javax.swing.JSlider();
        s14 = new javax.swing.JSlider();
        s16 = new javax.swing.JSlider();
        s17 = new javax.swing.JSlider();
        s18 = new javax.swing.JSlider();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        HSV.setBackground(new java.awt.Color(255, 255, 255));
        HSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HSV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(HSV);
        HSV.setBounds(360, 130, 280, 280);

        original.setBackground(new java.awt.Color(255, 255, 255));
        original.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        original.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(original);
        original.setBounds(40, 130, 280, 280);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(700, 30, 10, 450);

        s1.setMajorTickSpacing(50);
        s1.setMaximum(255);
        s1.setMinorTickSpacing(10);
        s1.setPaintLabels(true);
        s1.setPaintTicks(true);
        s1.setSnapToTicks(true);
        s1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s3.setMajorTickSpacing(50);
        s3.setMaximum(255);
        s3.setMinorTickSpacing(10);
        s3.setPaintLabels(true);
        s3.setPaintTicks(true);
        s3.setSnapToTicks(true);
        s3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s2.setMajorTickSpacing(50);
        s2.setMaximum(255);
        s2.setMinorTickSpacing(10);
        s2.setPaintLabels(true);
        s2.setPaintTicks(true);
        s2.setSnapToTicks(true);
        s2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s4.setMajorTickSpacing(50);
        s4.setMaximum(255);
        s4.setMinorTickSpacing(10);
        s4.setPaintLabels(true);
        s4.setPaintTicks(true);
        s4.setSnapToTicks(true);
        s4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s5.setMajorTickSpacing(50);
        s5.setMaximum(255);
        s5.setMinorTickSpacing(10);
        s5.setPaintLabels(true);
        s5.setPaintTicks(true);
        s5.setSnapToTicks(true);
        s5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s6.setMajorTickSpacing(50);
        s6.setMaximum(255);
        s6.setMinorTickSpacing(10);
        s6.setPaintLabels(true);
        s6.setPaintTicks(true);
        s6.setSnapToTicks(true);
        s6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("H-MIN");

        jLabel4.setText("H-MAX");

        jLabel5.setText("S-MIN");

        jLabel6.setText("S-MAX");

        jLabel7.setText("V-MIN");

        jLabel8.setText("V-MAX");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("RED", jPanel2);

        s7.setMajorTickSpacing(50);
        s7.setMaximum(255);
        s7.setMinorTickSpacing(10);
        s7.setPaintLabels(true);
        s7.setPaintTicks(true);
        s7.setSnapToTicks(true);
        s7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s9.setMajorTickSpacing(50);
        s9.setMaximum(255);
        s9.setMinorTickSpacing(10);
        s9.setPaintLabels(true);
        s9.setPaintTicks(true);
        s9.setSnapToTicks(true);
        s9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s8.setMajorTickSpacing(50);
        s8.setMaximum(255);
        s8.setMinorTickSpacing(10);
        s8.setPaintLabels(true);
        s8.setPaintTicks(true);
        s8.setSnapToTicks(true);
        s8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s10.setMajorTickSpacing(50);
        s10.setMaximum(255);
        s10.setMinorTickSpacing(10);
        s10.setPaintLabels(true);
        s10.setPaintTicks(true);
        s10.setSnapToTicks(true);
        s10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s11.setMajorTickSpacing(50);
        s11.setMaximum(255);
        s11.setMinorTickSpacing(10);
        s11.setPaintLabels(true);
        s11.setPaintTicks(true);
        s11.setSnapToTicks(true);
        s11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s12.setMajorTickSpacing(50);
        s12.setMaximum(255);
        s12.setMinorTickSpacing(10);
        s12.setPaintLabels(true);
        s12.setPaintTicks(true);
        s12.setSnapToTicks(true);
        s12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("H-MIN");

        jLabel10.setText("H-MAX");

        jLabel11.setText("S-MIN");

        jLabel12.setText("S-MAX");

        jLabel13.setText("V-MIN");

        jLabel14.setText("V-MAX");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s12, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s11, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s8, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s9, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s7, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s10, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BLUE", jPanel5);

        s13.setMajorTickSpacing(50);
        s13.setMaximum(255);
        s13.setMinorTickSpacing(10);
        s13.setPaintLabels(true);
        s13.setPaintTicks(true);
        s13.setSnapToTicks(true);
        s13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s15.setMajorTickSpacing(50);
        s15.setMaximum(255);
        s15.setMinorTickSpacing(10);
        s15.setPaintLabels(true);
        s15.setPaintTicks(true);
        s15.setSnapToTicks(true);
        s15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s14.setMajorTickSpacing(50);
        s14.setMaximum(255);
        s14.setMinorTickSpacing(10);
        s14.setPaintLabels(true);
        s14.setPaintTicks(true);
        s14.setSnapToTicks(true);
        s14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s16.setMajorTickSpacing(50);
        s16.setMaximum(255);
        s16.setMinorTickSpacing(10);
        s16.setPaintLabels(true);
        s16.setPaintTicks(true);
        s16.setSnapToTicks(true);
        s16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s17.setMajorTickSpacing(50);
        s17.setMaximum(255);
        s17.setMinorTickSpacing(10);
        s17.setPaintLabels(true);
        s17.setPaintTicks(true);
        s17.setSnapToTicks(true);
        s17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s18.setMajorTickSpacing(50);
        s18.setMaximum(255);
        s18.setMinorTickSpacing(10);
        s18.setPaintLabels(true);
        s18.setPaintTicks(true);
        s18.setSnapToTicks(true);
        s18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setText("H-MIN");

        jLabel16.setText("H-MAX");

        jLabel17.setText("S-MIN");

        jLabel18.setText("S-MAX");

        jLabel19.setText("V-MIN");

        jLabel20.setText("V-MAX");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s18, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s17, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s14, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s15, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s13, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s16, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("GREEN", jPanel6);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(720, 40, 350, 430);

        jButton1.setText("STOP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(520, 430, 140, 40);

        jButton2.setText("CAPTURE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 430, 140, 40);

        jButton3.setText("MOVE MOUSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(270, 430, 140, 40);
        jPanel1.add(lo);
        lo.setBounds(20, 0, 280, 140);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 420, 670, 10);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1150, 650);

        setSize(new java.awt.Dimension(1125, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void run()
    {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
       video = new VideoCapture(0);
        Mat sourceimg = new Mat();
        Mat dsting = new Mat();
     

        if(video.isOpened())
        {
            while(true)
            {
                Scalar redmin = new Scalar(s1.getValue(),s3.getValue(),s5.getValue());
                Scalar redmax = new Scalar(s2.getValue(),s4.getValue(),s6.getValue());
                
                Scalar bluemin = new Scalar(s7.getValue(),s9.getValue(),s11.getValue());
                Scalar bluemax = new Scalar(s8.getValue(),s10.getValue(),s12.getValue());
                
                Scalar greenmin = new Scalar(s13.getValue(),s15.getValue(),s17.getValue());
                Scalar greenmax = new Scalar(s14.getValue(),s16.getValue(),s18.getValue());
                   
                Mat circles = new Mat();
                Mat gcircles = new Mat();
                Mat bcircles = new Mat();
                Mat threshold1 = new Mat();
                Mat threshold2 = new Mat();
                Mat threshold3 = new Mat();
                Mat threshold4 = new Mat();
                Mat threshold5 = new Mat();
                Mat threshold6 = new Mat();
                Mat threshold7 = new Mat();
                

                video.read(sourceimg);
                if(!sourceimg.empty())
                {
                    Imgproc.cvtColor(sourceimg, dsting, Imgproc.COLOR_BGR2HSV);
                    Core.inRange(dsting, redmin, redmax, threshold1);
                    Core.inRange(dsting, bluemin, bluemax, threshold3);
                    Core.inRange(dsting, greenmin, greenmax, threshold5);
                    
                    Imgproc.erode(threshold1, threshold1, Imgproc.getStructuringElement(Imgproc.MORPH_RECT, new Size(12,12)));
                    Imgproc.dilate(threshold1, threshold1, Imgproc.getStructuringElement(Imgproc.MORPH_RECT, new Size(12,12)));

                    Imgproc.erode(threshold3, threshold3, Imgproc.getStructuringElement(Imgproc.MORPH_RECT, new Size(12,12)));
                    Imgproc.dilate(threshold3, threshold3, Imgproc.getStructuringElement(Imgproc.MORPH_RECT, new Size(12,12)));

                    Imgproc.erode(threshold5, threshold5, Imgproc.getStructuringElement(Imgproc.MORPH_RECT, new Size(12,12)));
                    Imgproc.dilate(threshold5, threshold5, Imgproc.getStructuringElement(Imgproc.MORPH_RECT, new Size(12,12)));

                    Imgproc.GaussianBlur(threshold1, threshold1, new Size(99,99), 0,0);
                    Imgproc.GaussianBlur(threshold3, threshold3, new Size(99,99), 0,0);
                    Imgproc.GaussianBlur(threshold5, threshold5, new Size(99,99), 0,0);
                    
                    List<MatOfPoint> contours = new ArrayList<MatOfPoint>();
                    Imgproc.HoughCircles(threshold1, circles, Imgproc.CV_HOUGH_GRADIENT, 2, threshold1.height()/1,200,100,0,0);
                    Imgproc.findContours(threshold1, contours, threshold2, Imgproc.RETR_LIST, Imgproc.CHAIN_APPROX_SIMPLE);
                    Imgproc.drawContours(sourceimg, contours, -1, new Scalar(255,0,0),1);
                    
                    List<MatOfPoint> gcontours = new ArrayList<MatOfPoint>();
                    Imgproc.HoughCircles(threshold5, gcircles, Imgproc.CV_HOUGH_GRADIENT, 2, threshold3.height()/1,200,100,0,0);
                    Imgproc.findContours(threshold5, gcontours, threshold4, Imgproc.RETR_LIST, Imgproc.CHAIN_APPROX_SIMPLE);
                    Imgproc.drawContours(sourceimg, gcontours, -1, new Scalar(255,0,0),1);
                    
                    List<MatOfPoint> bcontours = new ArrayList<MatOfPoint>();
                    Imgproc.HoughCircles(threshold3, circles, Imgproc.CV_HOUGH_GRADIENT, 2, threshold5.height()/1,200,100,0,0);
                    Imgproc.findContours(threshold3, bcontours, threshold6, Imgproc.RETR_LIST, Imgproc.CHAIN_APPROX_SIMPLE);
                    Imgproc.drawContours(sourceimg, bcontours, -1, new Scalar(255,0,0),1);
                    
                    Core.bitwise_or(threshold1, threshold3, threshold7);
                    Core.bitwise_or(threshold7, threshold5, threshold7);

                    BufferedImage srcimg = matToBufferedImage(sourceimg);
                    this.original.setIcon(new ImageIcon(srcimg));
                 
                    BufferedImage srcimg2 = matToBufferedImage(threshold7);
                    this.HSV.setIcon(new ImageIcon(srcimg2));
                    
                    try {
                        Mouse m = new Mouse();
                        boolean blue = false;
                        blue = (threshold6.size().height>0 || threshold6.size().width>0);
                        boolean green = false;
                        green = (threshold4.size().height>0 || threshold4.size().width>0);
                         
                        if(blue)
                        {
                            m.leftClick();
                        }
                        
                        if(green) 
                        {
                            m.rightclick();
                        }
                        int x=m.getX(contours);
                        int y=m.getY(contours);
                        if(x!=0&&y!=0)
                        {
                           m.moveMouse(x, y);
                        }
                    } catch (AWTException ex) {
                        Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Camera Cannot Capture Image");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Camera Cannot Work!");

        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        t = new Thread(this);
        t.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        t.stop();
        video.release();
        this.original.setIcon(new ImageIcon());
        
        ImageIcon img3=new ImageIcon(getClass().getResource("/Image/or.jpg"));
        Image img4= img3.getImage().getScaledInstance(original.getHeight(),original.getWidth(),Image.SCALE_SMOOTH);
        original.setIcon(new ImageIcon(img4));
        
        ImageIcon img5=new ImageIcon(getClass().getResource("/Image/or.jpg"));
        Image img6= img5.getImage().getScaledInstance(HSV.getHeight(),HSV.getWidth(),Image.SCALE_SMOOTH);
        HSV.setIcon(new ImageIcon(img6));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Dashboard().setVisible(true);
                } catch (AWTException ex) {
                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel HSV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lo;
    public javax.swing.JLabel original;
    private javax.swing.JSlider s1;
    private javax.swing.JSlider s10;
    private javax.swing.JSlider s11;
    private javax.swing.JSlider s12;
    private javax.swing.JSlider s13;
    private javax.swing.JSlider s14;
    private javax.swing.JSlider s15;
    private javax.swing.JSlider s16;
    private javax.swing.JSlider s17;
    private javax.swing.JSlider s18;
    private javax.swing.JSlider s2;
    private javax.swing.JSlider s3;
    private javax.swing.JSlider s4;
    private javax.swing.JSlider s5;
    private javax.swing.JSlider s6;
    private javax.swing.JSlider s7;
    private javax.swing.JSlider s8;
    private javax.swing.JSlider s9;
    // End of variables declaration//GEN-END:variables
}
